# Mod Properties
org.gradle.java.home=E:/JDK25
mod_name=Vanilla Outsider: Better Dogs
mod_version=5.0.92+26.3
maven_group=net.vanillaoutsider
archives_base_name=vanilla-outsider-better-dogs

# Dependencies
minecraft_version=26.3-snapshot-6
fabric_loader_version=0.19.3
fabric_version=0.156.1+26.3
dasik_library_version=1.8.37
