// Copyright (C) 2026 Dasik (Rifaditya) | GNU GPLv3
// Verified against: Minecraft 26.2
package net.vanillaoutsider.betterdogs.config;

import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import dev.isxander.yacl3.api.ConfigCategory;
import dev.isxander.yacl3.api.Option;
import dev.isxander.yacl3.api.OptionDescription;
import dev.isxander.yacl3.api.OptionGroup;
import dev.isxander.yacl3.api.YetAnotherConfigLib;
import dev.isxander.yacl3.api.controller.DoubleFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.DoubleSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.DropdownStringControllerBuilder;
import dev.isxander.yacl3.api.controller.FloatFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.FloatSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.List;

public class YaclScreenHelper {
    public static ConfigScreenFactory<?> createFactory() {
        return YaclScreenHelper::createScreen;
    }

    public static Screen createScreen(Screen parent) {
        BetterDogsConfig config = BetterDogsConfig.get();

        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("config.betterdogs.title"))
                .save(BetterDogsConfig::save)
                
                // === GENERAL CATEGORY ===
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.betterdogs.category.general"))
                        .tooltip(Component.translatable("config.betterdogs.warning"))
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.globalSpeedBuff"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.globalSpeedBuff.description")))
                                .binding(0.20, () -> config.globalSpeedBuff, val -> config.globalSpeedBuff = val)
                                .controller(DoubleFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableStormAnxiety"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableStormAnxiety.description")))
                                .binding(true, () -> config.enableStormAnxiety, val -> config.enableStormAnxiety = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableCliffSafety"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableCliffSafety.description")))
                                .binding(true, () -> config.enableCliffSafety, val -> config.enableCliffSafety = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableFleeLowHealth"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableFleeLowHealth.description")))
                                .binding(true, () -> config.enableFleeLowHealth, val -> config.enableFleeLowHealth = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableFriendlyFireProtection"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableFriendlyFireProtection.description")))
                                .binding(true, () -> config.enableFriendlyFireProtection, val -> config.enableFriendlyFireProtection = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableDogsEatRawGroundFood"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableDogsEatRawGroundFood.description")))
                                .binding(true, () -> config.enableDogsEatRawGroundFood, val -> config.enableDogsEatRawGroundFood = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.creeperAwareness"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.creeperAwareness.description")))
                                .binding(true, () -> config.creeperAwareness, val -> config.creeperAwareness = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enablePackFlankingTactics"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enablePackFlankingTactics.description")))
                                .binding(true, () -> config.enablePackFlankingTactics, val -> config.enablePackFlankingTactics = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableDogsEatCookedGroundFood"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableDogsEatCookedGroundFood.description")))
                                .binding(true, () -> config.enableDogsEatCookedGroundFood, val -> config.enableDogsEatCookedGroundFood = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableRefuseGroundFood"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableRefuseGroundFood.description")))
                                .binding(true, () -> config.enableRefuseGroundFood, val -> config.enableRefuseGroundFood = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.refuseGroundFoodChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.refuseGroundFoodChance.description")))
                                .binding(30, () -> config.refuseGroundFoodChance, val -> config.refuseGroundFoodChance = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableFavoriteTreats"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableFavoriteTreats.description")))
                                .binding(true, () -> config.enableFavoriteTreats, val -> config.enableFavoriteTreats = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.pacifistGuardBuffs"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistGuardBuffs.description")))
                                .binding(false, () -> config.pacifistGuardBuffs, val -> config.pacifistGuardBuffs = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableInbredCuring"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableInbredCuring.description")))
                                .binding(false, () -> config.enableInbredCuring, val -> config.enableInbredCuring = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.followCatchUpSpeed"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.followCatchUpSpeed.description")))
                                .binding(1.5, () -> config.followCatchUpSpeed, val -> config.followCatchUpSpeed = val)
                                .controller(DoubleFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.followCatchUpThreshold"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.followCatchUpThreshold.description")))
                                .binding(10.0, () -> config.followCatchUpThreshold, val -> config.followCatchUpThreshold = val)
                                .controller(DoubleFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.teleportToOwnerSpread"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.teleportToOwnerSpread.description")))
                                .binding(4.0, () -> config.teleportToOwnerSpread, val -> config.teleportToOwnerSpread = val)
                                .controller(DoubleFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.teleportMultiplier"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.teleportMultiplier.description")))
                                .binding(2.0, () -> config.teleportMultiplier, val -> config.teleportMultiplier = val)
                                .controller(DoubleFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("config.betterdogs.stormAnxietyTriggerChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.stormAnxietyTriggerChance.description")))
                                .binding(0.01f, () -> config.stormAnxietyTriggerChance, val -> config.stormAnxietyTriggerChance = val)
                                .controller(FloatFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("config.betterdogs.stormWhineChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.stormWhineChance.description")))
                                .binding(0.02f, () -> config.stormWhineChance, val -> config.stormWhineChance = val)
                                .controller(FloatFieldControllerBuilder::create)
                                .build())
                        .build())

                // === PERSONALITIES CATEGORY ===
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.betterdogs.category.personalities"))
                        .tooltip(Component.translatable("config.betterdogs.warning"))
                        
                        // Aggressive Group
                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Aggressive"))
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveHealthBonus"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveHealthBonus.description")))
                                        .binding(-10.0, () -> config.aggressiveHealthBonus, val -> config.aggressiveHealthBonus = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveSpeedModifier"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveSpeedModifier.description")))
                                        .binding(0.15, () -> config.aggressiveSpeedModifier, val -> config.aggressiveSpeedModifier = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveDetectionRange"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveDetectionRange.description")))
                                        .binding(20.0, () -> config.aggressiveDetectionRange, val -> config.aggressiveDetectionRange = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveChaseDistance"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveChaseDistance.description")))
                                        .binding(50.0, () -> config.aggressiveChaseDistance, val -> config.aggressiveChaseDistance = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveDamageModifier"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveDamageModifier.description")))
                                        .binding(0.50, () -> config.aggressiveDamageModifier, val -> config.aggressiveDamageModifier = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveFollowStart"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveFollowStart.description")))
                                        .binding(50.0f, () -> config.aggressiveFollowStart, val -> config.aggressiveFollowStart = val)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveFollowStop"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveFollowStop.description")))
                                        .binding(2.0f, () -> config.aggressiveFollowStop, val -> config.aggressiveFollowStop = val)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.betterdogs.aggressiveFleeChance"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveFleeChance.description")))
                                        .binding(10, () -> config.aggressiveFleeChance, val -> config.aggressiveFleeChance = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                        .build())
                                .build())

                        // Pacifist Group
                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Pacifist"))
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.pacifistHealthBonus"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistHealthBonus.description")))
                                        .binding(20.0, () -> config.pacifistHealthBonus, val -> config.pacifistHealthBonus = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.pacifistSpeedModifier"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistSpeedModifier.description")))
                                        .binding(-0.10, () -> config.pacifistSpeedModifier, val -> config.pacifistSpeedModifier = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.pacifistDamageModifier"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistDamageModifier.description")))
                                        .binding(-0.30, () -> config.pacifistDamageModifier, val -> config.pacifistDamageModifier = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.pacifistKnockbackModifier"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistKnockbackModifier.description")))
                                        .binding(0.5, () -> config.pacifistKnockbackModifier, val -> config.pacifistKnockbackModifier = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.betterdogs.pacifistFollowStart"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistFollowStart.description")))
                                        .binding(5.0f, () -> config.pacifistFollowStart, val -> config.pacifistFollowStart = val)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.betterdogs.pacifistFollowStop"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistFollowStop.description")))
                                        .binding(2.0f, () -> config.pacifistFollowStop, val -> config.pacifistFollowStop = val)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.betterdogs.pacifistFleeChance"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistFleeChance.description")))
                                        .binding(100, () -> config.pacifistFleeChance, val -> config.pacifistFleeChance = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                        .build())
                                .build())

                        // Normal Group
                        .group(OptionGroup.createBuilder()
                                .name(Component.literal("Normal"))
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.normalHealthBonus"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.normalHealthBonus.description")))
                                        .binding(0.0, () -> config.normalHealthBonus, val -> config.normalHealthBonus = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.normalSpeedModifier"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.normalSpeedModifier.description")))
                                        .binding(0.0, () -> config.normalSpeedModifier, val -> config.normalSpeedModifier = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.betterdogs.normalDamageModifier"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.normalDamageModifier.description")))
                                        .binding(0.0, () -> config.normalDamageModifier, val -> config.normalDamageModifier = val)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.betterdogs.normalFollowStart"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.normalFollowStart.description")))
                                        .binding(10.0f, () -> config.normalFollowStart, val -> config.normalFollowStart = val)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.betterdogs.normalFollowStop"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.normalFollowStop.description")))
                                        .binding(2.0f, () -> config.normalFollowStop, val -> config.normalFollowStop = val)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.betterdogs.normalFleeChance"))
                                        .description(OptionDescription.of(Component.translatable("config.betterdogs.normalFleeChance.description")))
                                        .binding(50, () -> config.normalFleeChance, val -> config.normalFleeChance = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                        .build())
                                .build())
                        .build())

                // === BREEDING & GENETICS CATEGORY ===
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.betterdogs.category.breeding"))
                        .tooltip(Component.translatable("config.betterdogs.warning"))
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.spawnChanceNormal"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.spawnChanceNormal.description")))
                                .binding(60, () -> config.spawnChanceNormal, val -> config.spawnChanceNormal = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.spawnChanceAggressive"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.spawnChanceAggressive.description")))
                                .binding(20, () -> config.spawnChanceAggressive, val -> config.spawnChanceAggressive = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.spawnChancePacifist"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.spawnChancePacifist.description")))
                                .binding(20, () -> config.spawnChancePacifist, val -> config.spawnChancePacifist = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.wolfSpawnMultiplier"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.wolfSpawnMultiplier.description")))
                                .binding(1.5, () -> config.wolfSpawnMultiplier, val -> config.wolfSpawnMultiplier = val)
                                .controller(DoubleFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.spawnGroupMin"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.spawnGroupMin.description")))
                                .binding(4, () -> config.spawnGroupMin, val -> config.spawnGroupMin = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 16).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.spawnGroupMax"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.spawnGroupMax.description")))
                                .binding(8, () -> config.spawnGroupMax, val -> config.spawnGroupMax = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 32).step(1))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.enableExpandedBiomes"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.enableExpandedBiomes.description")))
                                .binding(false, () -> config.enableExpandedBiomes, val -> config.enableExpandedBiomes = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.breedingSameParentChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.breedingSameParentChance.description")))
                                .binding(80, () -> config.breedingSameParentChance, val -> config.breedingSameParentChance = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.breedingSameParentOtherChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.breedingSameParentOtherChance.description")))
                                .binding(10, () -> config.breedingSameParentOtherChance, val -> config.breedingSameParentOtherChance = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.breedingMixedDominantChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.breedingMixedDominantChance.description")))
                                .binding(40, () -> config.breedingMixedDominantChance, val -> config.breedingMixedDominantChance = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.breedingMixedRecessiveChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.breedingMixedRecessiveChance.description")))
                                .binding(20, () -> config.breedingMixedRecessiveChance, val -> config.breedingMixedRecessiveChance = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.breedingDilutedNormalChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.breedingDilutedNormalChance.description")))
                                .binding(50, () -> config.breedingDilutedNormalChance, val -> config.breedingDilutedNormalChance = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.breedingDilutedOtherChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.breedingDilutedOtherChance.description")))
                                .binding(25, () -> config.breedingDilutedOtherChance, val -> config.breedingDilutedOtherChance = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.wolfMinScale"))
                                .binding(0.70, () -> config.wolfMinScale, val -> config.wolfMinScale = val)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.0625, 16.0).step(0.05))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.wolfMinScale.description")))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.betterdogs.wolfMaxScale"))
                                .binding(1.45, () -> config.wolfMaxScale, val -> config.wolfMaxScale = val)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.0625, 16.0).step(0.05))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.wolfMaxScale.description")))
                                .build())
                        .build())

                // === TERRITORIALITY CATEGORY ===
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.betterdogs.category.territoriality"))
                        .tooltip(Component.translatable("config.betterdogs.warning"))
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("config.betterdogs.wildHuntHealthThreshold"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.wildHuntHealthThreshold.description")))
                                .binding(0.5f, () -> config.wildHuntHealthThreshold, val -> config.wildHuntHealthThreshold = val)
                                .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.0f, 1.0f).step(0.05f))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixAAWar"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixAAWar.description")))
                                .binding(80, () -> config.terrMatrixAAWar, val -> config.terrMatrixAAWar = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixAAMerge"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixAAMerge.description")))
                                .binding(10, () -> config.terrMatrixAAMerge, val -> config.terrMatrixAAMerge = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixANWar"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixANWar.description")))
                                .binding(50, () -> config.terrMatrixANWar, val -> config.terrMatrixANWar = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixANMerge"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixANMerge.description")))
                                .binding(40, () -> config.terrMatrixANMerge, val -> config.terrMatrixANMerge = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixAPWar"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixAPWar.description")))
                                .binding(10, () -> config.terrMatrixAPWar, val -> config.terrMatrixAPWar = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixAPMerge"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixAPMerge.description")))
                                .binding(50, () -> config.terrMatrixAPMerge, val -> config.terrMatrixAPMerge = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixNNWar"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixNNWar.description")))
                                .binding(20, () -> config.terrMatrixNNWar, val -> config.terrMatrixNNWar = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixNNMerge"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixNNMerge.description")))
                                .binding(50, () -> config.terrMatrixNNMerge, val -> config.terrMatrixNNMerge = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixNPWar"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixNPWar.description")))
                                .binding(5, () -> config.terrMatrixNPWar, val -> config.terrMatrixNPWar = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixNPMerge"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixNPMerge.description")))
                                .binding(45, () -> config.terrMatrixNPMerge, val -> config.terrMatrixNPMerge = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixPPWar"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixPPWar.description")))
                                .binding(0, () -> config.terrMatrixPPWar, val -> config.terrMatrixPPWar = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.terrMatrixPPMerge"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.terrMatrixPPMerge.description")))
                                .binding(50, () -> config.terrMatrixPPMerge, val -> config.terrMatrixPPMerge = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .build())

                // === GIFTS CATEGORY ===
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.betterdogs.category.gifts"))
                        .tooltip(Component.translatable("config.betterdogs.warning"))
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.giftCooldownMin"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.giftCooldownMin.description")))
                                .binding(12000, () -> config.giftCooldownMin, val -> config.giftCooldownMin = val)
                                .controller(IntegerFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.giftCooldownMax"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.giftCooldownMax.description")))
                                .binding(18000, () -> config.giftCooldownMax, val -> config.giftCooldownMax = val)
                                .controller(IntegerFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("config.betterdogs.giftTriggerChance"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.giftTriggerChance.description")))
                                .binding(0.01f, () -> config.giftTriggerChance, val -> config.giftTriggerChance = val)
                                .controller(FloatFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.betterdogs.demeritAccidentalAttacks"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.demeritAccidentalAttacks.description")))
                                .binding(true, () -> config.demeritAccidentalAttacks, val -> config.demeritAccidentalAttacks = val)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.aggressiveGiftBone"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveGiftBone.description")))
                                .binding(40, () -> config.aggressiveGiftBone, val -> config.aggressiveGiftBone = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.aggressiveGiftFlesh"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveGiftFlesh.description")))
                                .binding(35, () -> config.aggressiveGiftFlesh, val -> config.aggressiveGiftFlesh = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.aggressiveGiftArrow"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.aggressiveGiftArrow.description")))
                                .binding(15, () -> config.aggressiveGiftArrow, val -> config.aggressiveGiftArrow = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.pacifistGiftBerries"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistGiftBerries.description")))
                                .binding(30, () -> config.pacifistGiftBerries, val -> config.pacifistGiftBerries = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.pacifistGiftSeeds"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistGiftSeeds.description")))
                                .binding(25, () -> config.pacifistGiftSeeds, val -> config.pacifistGiftSeeds = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.pacifistGiftFlower"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistGiftFlower.description")))
                                .binding(20, () -> config.pacifistGiftFlower, val -> config.pacifistGiftFlower = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.betterdogs.pacifistGiftMushroom"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.pacifistGiftMushroom.description")))
                                .binding(15, () -> config.pacifistGiftMushroom, val -> config.pacifistGiftMushroom = val)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                .build())
                        .build())

                // === VISUAL & PERFORMANCE CATEGORY ===
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.betterdogs.category.performance"))
                        .tooltip(Component.translatable("config.betterdogs.warning"))
                        .option(Option.<String>createBuilder()
                                .name(Component.translatable("config.betterdogs.guardParticleDensity"))
                                .description(OptionDescription.of(Component.translatable("config.betterdogs.guardParticleDensity.description")))
                                .binding("medium", () -> config.guardParticleDensity, val -> config.guardParticleDensity = val)
                                .controller(opt -> DropdownStringControllerBuilder.create(opt)
                                        .values(List.of("high", "medium", "low", "off")))
                                .build())
                        .build())
                .build()
                .generateScreen(parent);
    }
}
